# -*- coding: utf-8 -*-
"""
Generated by ArcGIS ModelBuilder on : 2024-06-18 15:27:13
"""
import arcpy
from arcpy.ia import *
from arcpy.ia import *
from arcpy.ia import *

def slope():  # slope

    # To allow overwriting outputs change overwriteOutput option to True.
    arcpy.env.overwriteOutput = False

    # Check out any necessary licenses.
    arcpy.CheckOutExtension("spatial")
    arcpy.CheckOutExtension("ImageExt")
    arcpy.CheckOutExtension("ImageAnalyst")

    arcpy.ImportToolbox(r"d:\arcgis\Resources\ArcToolbox\toolboxes\Conversion Tools.tbx")
    tza_adm2_1967 = "tza_adm2_1967"
    slope_tif = arcpy.Raster("backup\\slope.tif")
    cellarea_tif = arcpy.Raster("cellarea.tif")

    # Process: Project Raster (Project Raster) (management)
    slope_ProjectRaster_tif = "C:\\Users\\YAWEN L\\Dropbox\\GIS_Yawen\\gis_input\\process\\slope_ProjectRaster\\slope_ProjectRaster.tif"
    arcpy.management.ProjectRaster(in_raster=slope_tif, out_raster=slope_ProjectRaster_tif, out_coor_system="PROJCS[\"WGS_1984_UTM_Zone_37S\",GEOGCS[\"GCS_WGS_1984\",DATUM[\"D_WGS_1984\",SPHEROID[\"WGS_1984\",6378137.0,298.257223563]],PRIMEM[\"Greenwich\",0.0],UNIT[\"Degree\",0.0174532925199433]],PROJECTION[\"Transverse_Mercator\"],PARAMETER[\"False_Easting\",500000.0],PARAMETER[\"False_Northing\",10000000.0],PARAMETER[\"Central_Meridian\",39.0],PARAMETER[\"Scale_Factor\",0.9996],PARAMETER[\"Latitude_Of_Origin\",0.0],UNIT[\"Meter\",1.0]]")
    slope_ProjectRaster_tif = arcpy.Raster(slope_ProjectRaster_tif)

    # Process: Dissolve (Dissolve) (management)
    tza_border_shp = "C:\\Users\\YAWEN L\\Dropbox\\GIS_Yawen\\gis_input\\process\\tza_border\\tza_border.shp"
    arcpy.management.Dissolve(in_features=tza_adm2_1967, out_feature_class=tza_border_shp)

    # Process: Clip Raster (Clip Raster) (management)
    slope_Clip_tif = "C:\\Users\\YAWEN L\\Dropbox\\GIS_Yawen\\gis_input\\process\\slope_Clip\\slope_Clip.tif"
    arcpy.management.Clip(in_raster=slope_ProjectRaster_tif, rectangle="-548018.917763777 8698528.07134324 658181.608772465 9890193.69444369", out_raster=slope_Clip_tif, in_template_dataset=tza_border_shp, clipping_geometry="ClippingGeometry")
    slope_Clip_tif = arcpy.Raster(slope_Clip_tif)

    # Process: Project Raster (2) (Project Raster) (management)
    cellarea_ProjectRaster_tif = "C:\\Users\\YAWEN L\\Dropbox\\GIS_Yawen\\gis_input\\process\\cellarea_ProjectRaster\\cellarea_ProjectRaster.tif"
    arcpy.management.ProjectRaster(in_raster=cellarea_tif, out_raster=cellarea_ProjectRaster_tif, out_coor_system="PROJCS[\"WGS_1984_UTM_Zone_37S\",GEOGCS[\"GCS_WGS_1984\",DATUM[\"D_WGS_1984\",SPHEROID[\"WGS_1984\",6378137.0,298.257223563]],PRIMEM[\"Greenwich\",0.0],UNIT[\"Degree\",0.0174532925199433]],PROJECTION[\"Transverse_Mercator\"],PARAMETER[\"False_Easting\",500000.0],PARAMETER[\"False_Northing\",10000000.0],PARAMETER[\"Central_Meridian\",39.0],PARAMETER[\"Scale_Factor\",0.9996],PARAMETER[\"Latitude_Of_Origin\",0.0],UNIT[\"Meter\",1.0]]")
    cellarea_ProjectRaster_tif = arcpy.Raster(cellarea_ProjectRaster_tif)

    # Process: Clip Raster (2) (Clip Raster) (management)
    cellarea_Clip_tif = "C:\\Users\\YAWEN L\\Dropbox\\GIS_Yawen\\gis_input\\process\\cellarea_Clip\\cellarea_Clip.tif"
    arcpy.management.Clip(in_raster=cellarea_ProjectRaster_tif, rectangle="-548018.917763777 8698528.07134324 658181.608772465 9890193.69444369", out_raster=cellarea_Clip_tif, in_template_dataset=tza_border_shp, clipping_geometry="ClippingGeometry")
    cellarea_Clip_tif = arcpy.Raster(cellarea_Clip_tif)

    # Process: Raster Calculator (Raster Calculator) (ia)
    mutiply_slope = "C:\\Users\\YAWEN L\\Dropbox\\GIS_Yawen\\gis_input\\process\\multiply_slope\\mutiply_slope"
    Raster_Calculator = mutiply_slope
    mutiply_slope =  slope_Clip_tif  *  cellarea_Clip_tif
    mutiply_slope.save(Raster_Calculator)


    # Process: Zonal Statistics as Table (Zonal Statistics as Table) (ia)
    slope_statistics_dbf = "C:\\Users\\YAWEN L\\Dropbox\\GIS_Yawen\\gis_input\\process\\slope_statistics\\slope_statistics.dbf"
    district_slope = "C:\\Users\\YAWEN L\\Dropbox\\GIS_Yawen\\gis_input\\process\\district_slope"
    arcpy.ia.ZonalStatisticsAsTable(tza_adm2_1967, "distname19", mutiply_slope, slope_statistics_dbf, "DATA", "SUM", "CURRENT_SLICE", [90], "AUTO_DETECT", "ARITHMETIC", 360, district_slope)
    .save(Zonal_Statistics_as_Table)


    # Process: Zonal Statistics as Table (2) (Zonal Statistics as Table) (ia)
    cellarea_statistics_dbf = "C:\\Users\\YAWEN L\\Dropbox\\GIS_Yawen\\gis_input\\process\\cellarea_statistics\\cellarea_statistics.dbf"
    district_cellarea = "C:\\Users\\YAWEN L\\Dropbox\\GIS_Yawen\\gis_input\\process\\district_cellarea\\district_cellarea"
    arcpy.ia.ZonalStatisticsAsTable(tza_adm2_1967, "distname19", cellarea_ProjectRaster_tif, cellarea_statistics_dbf, "DATA", "SUM", "CURRENT_SLICE", [90], "AUTO_DETECT", "ARITHMETIC", 360, district_cellarea)
    .save(Zonal_Statistics_as_Table_2_)


    # Process: Join Field (Join Field) (management)
    district_slope_2_ = arcpy.management.JoinField(in_data=slope_statistics_dbf, in_field="distname19", join_table=cellarea_statistics_dbf, join_field="distname19", fields=["SUM"], fm_option="NOT_USE_FM")[0]

    # Process: Calculate Field (Calculate Field) (management)
    slope_statistics_dbf_2_ = arcpy.management.CalculateField(in_table=district_slope_2_, field="Avrg_sl", expression="!SUM! / !SUM_1! / 1000")[0]

    # Process: Table To Excel (Table To Excel) (conversion)
    slope_xlsx = "C:\\Users\\YAWEN L\\Dropbox\\GIS_Yawen\\gis_input\\output\\slope\\slope.xlsx"
    arcpy.conversion.TableToExcel(Input_Table=[slope_statistics_dbf_2_], Output_Excel_File=slope_xlsx)

if __name__ == '__main__':
    # Global Environment settings
    with arcpy.EnvManager(scratchWorkspace="C:\\Users\\YAWEN L\\Dropbox\\GIS_Yawen\\gis_input\\GIS folder\\TANZANIA\\TANZANIA.gdb", workspace="C:\\Users\\YAWEN L\\Dropbox\\GIS_Yawen\\gis_input\\GIS folder\\TANZANIA\\TANZANIA.gdb"):
        slope()
