# -*- coding: utf-8 -*-
"""
Generated by ArcGIS ModelBuilder on : 2024-07-04 14:44:06
"""
import arcpy

def roads():  # roads

    # To allow overwriting outputs change overwriteOutput option to True.
    arcpy.env.overwriteOutput = False

    arcpy.ImportToolbox(r"d:\arcgis\Resources\ArcToolbox\toolboxes\Data Management Tools.tbx")
    arcpy.ImportToolbox(r"d:\arcgis\Resources\ArcToolbox\toolboxes\Conversion Tools.tbx")
    tza_adm2_1967 = "tza_adm2_1967"
    roads_1968_projected = "roads_1968_projected"

    # Process: Intersect (Intersect) (analysis)
    roads_districts_intersect_shp = "C:\\Users\\YAWEN L\\Dropbox\\GIS_Yawen\\gis_input\\process\\roads_districts_intersect\\roads_districts_intersect.shp"
    arcpy.analysis.Intersect(in_features=[[tza_adm2_1967, ""], [roads_1968_projected, ""]], out_feature_class=roads_districts_intersect_shp, join_attributes="ALL", output_type="LINE")

    # Process: Add Field (Add Field) (management)
    roads_districts_intersect_shp_4_ = arcpy.management.AddField(in_table=roads_districts_intersect_shp, field_name="lth_divi", field_type="FLOAT")[0]

    # Process: Calculate Geometry Attributes (2) (Calculate Geometry Attributes) (management)
    roads_districts_intersect_shp_2_ = arcpy.management.CalculateGeometryAttributes(in_features=roads_districts_intersect_shp_4_, geometry_property=[["lth_divi", "LENGTH"]], length_unit="KILOMETERS", coordinate_system="PROJCS[\"WGS_1984_UTM_Zone_37S\",GEOGCS[\"GCS_WGS_1984\",DATUM[\"D_WGS_1984\",SPHEROID[\"WGS_1984\",6378137.0,298.257223563]],PRIMEM[\"Greenwich\",0.0],UNIT[\"Degree\",0.0174532925199433]],PROJECTION[\"Transverse_Mercator\"],PARAMETER[\"False_Easting\",500000.0],PARAMETER[\"False_Northing\",10000000.0],PARAMETER[\"Central_Meridian\",39.0],PARAMETER[\"Scale_Factor\",0.9996],PARAMETER[\"Latitude_Of_Origin\",0.0],UNIT[\"Meter\",1.0]]")[0]

    # Process: Summary Statistics (Summary Statistics) (analysis)
    roads_totallength_dbf = "C:\\Users\\YAWEN L\\Dropbox\\GIS_Yawen\\gis_input\\process\\roads_totallength\\roads_totallength.dbf"
    arcpy.analysis.Statistics(in_table=roads_districts_intersect_shp_2_, out_table=roads_totallength_dbf, statistics_fields=[["lth_divi", "SUM"]], case_field=["distname19"])

    # Process: Calculate Geometry Attributes (3) (Calculate Geometry Attributes) (management)
    tza_adm2_1967_2_ = arcpy.management.CalculateGeometryAttributes(in_features=tza_adm2_1967, geometry_property=[["Area", "AREA"]], area_unit="SQUARE_KILOMETERS", coordinate_system="PROJCS[\"WGS_1984_UTM_Zone_37S\",GEOGCS[\"GCS_WGS_1984\",DATUM[\"D_WGS_1984\",SPHEROID[\"WGS_1984\",6378137.0,298.257223563]],PRIMEM[\"Greenwich\",0.0],UNIT[\"Degree\",0.0174532925199433]],PROJECTION[\"Transverse_Mercator\"],PARAMETER[\"False_Easting\",500000.0],PARAMETER[\"False_Northing\",10000000.0],PARAMETER[\"Central_Meridian\",39.0],PARAMETER[\"Scale_Factor\",0.9996],PARAMETER[\"Latitude_Of_Origin\",0.0],UNIT[\"Meter\",1.0]]")[0]

    # Process: Join Field (Join Field) (management)
    roads_totallength_dbf_2_ = arcpy.management.JoinField(in_data=roads_totallength_dbf, in_field="distname19", join_table=tza_adm2_1967_2_, join_field="distname19", fields=["Area"])[0]

    # Process: Table To Excel (Table To Excel) (conversion)
    length_of_roads_xlsx = "C:\\Users\\YAWEN L\\Dropbox\\GIS_Yawen\\gis_input\\output\\length_of_roads\\length of roads.xlsx"
    arcpy.conversion.TableToExcel(Input_Table=[roads_totallength_dbf_2_], Output_Excel_File=length_of_roads_xlsx)

if __name__ == '__main__':
    # Global Environment settings
    with arcpy.EnvManager(scratchWorkspace="C:\\Users\\YAWEN L\\Dropbox\\GIS_Yawen\\gis_input\\GIS folder\\TANZANIA\\TANZANIA.gdb", workspace="C:\\Users\\YAWEN L\\Dropbox\\GIS_Yawen\\gis_input\\GIS folder\\TANZANIA\\TANZANIA.gdb"):
        roads()
